<?php
/**
 * Central database configuration.
 *
 * Every other file that needs the database includes THIS file
 * and uses the $pdo connection it creates. Do not scatter
 * database credentials across other files.
 */

// On the live server, env.php (generated by the GitHub Actions
// deploy from repository secrets, never committed) defines the real
// credentials. Anything it leaves out falls back to the local XAMPP
// defaults below.
if (is_file(__DIR__ . '/env.php')) {
    require __DIR__ . '/env.php';
}

// ---- Local XAMPP defaults ----
defined('DB_HOST') || define('DB_HOST', 'localhost');
defined('DB_NAME') || define('DB_NAME', 'namanga_resource_centre');
defined('DB_USER') || define('DB_USER', 'root');
defined('DB_PASS') || define('DB_PASS', ''); // XAMPP's default MySQL root password is empty
// ---------------------------------------------------------------

// Application environment: set to false on a live/public server
// so raw PHP/database errors are never shown to visitors.
defined('APP_DEBUG') || define('APP_DEBUG', true);

$dsn = 'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=utf8mb4';

$options = [
    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES   => false,
];

try {
    $pdo = new PDO($dsn, DB_USER, DB_PASS, $options);
} catch (PDOException $e) {
    if (APP_DEBUG) {
        die('Database connection error: ' . htmlspecialchars($e->getMessage()));
    }
    http_response_code(500);
    die('We are unable to connect to the database right now. Please try again later.');
}
